### ISSUE TITLE
backend issue with scraping 

### ISSUE THREAD

**Issue by acierp** [jevonmao/SMHS-Schedule-Backend#6]
upon aeries' fairly short ratelimit, a 401 (invalid login) is given when a ratelimit is passed by aeries on the backend's side. I see the need for rotating proxies, likewise to most scraping sites along with a ratelimiting implementation of your own to the aeries-student.herokuapp.com backend to prevent such abuse or **for grades to be kept cached for each user (even when logged out) & updated on an interval.**

**Comment by jevonmao** [comment]
thx for the insightful and technical comments, i can tell u know what u are doing. but fyi:
![image](https://user-images.githubusercontent.com/64660730/138534268-9602df25-3a04-4379-983c-80a28d9aed19.jpeg)
